# This program generates the "look-and-say" sequence.
# The sequence is generated by describing the previous term.
# For example, starting with "1":
# 1 -> one 1 -> "11"
# 11 -> two 1s -> "21"
# 21 -> one 2, one 1 -> "1211"

from codetiming import Timer

def look_and_say(sequence, n_terms):
    
    # for _ in range(n_terms):
    for index in range(1, n_terms + 1):
        # print(f"{index}: len {len(sequence)}: {sequence}")
        print(f"{index}: len {len(sequence)}")
        next_seq = ""
        i = 0
        while i < len(sequence):
            count = 1
            while i + 1 < len(sequence) and sequence[i] == sequence[i + 1]:
                i += 1
                count += 1
            next_seq += str(count) + sequence[i]
            i += 1
        sequence = next_seq

# Ask user:
seq = input("Enter starting sequence (default is '1'): ") or "1"
terms = int(input("How many terms do you want to generate? "))
t = Timer()
t.start()
print(f"Generating {terms} terms of the look-and-say sequence starting with '{seq}':")
look_and_say(seq, terms)
t.stop()
